#version: "3.8"

services:

  comunicacao:
    build: .
    container_name: comunicacao
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/comunicacao?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      -  SPRING_DATASOURCE_PASSWORD=1234
      - EMAIL_URL=notificacao:8081/email
      - TZ=America/Sao_Paulo

    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - notificacao

  notificacao:
    build: ../notificacao
    container_name: notificacao
    restart: always
    ports:
      - "8081:8081"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: comunicacao
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default:
    driver: bridge